// Random school jokes :)

const jokes: string[] = [
  "Why did the math book look sad? Because it had too many problems.",
  "What did one math book say to the other? Don't bother me, I've got my own problems!",
  "Why did the student eat his homework? Because the teacher said it was a piece of cake!",
  "Why was the teacher cross-eyed? Because she couldn't control her pupils!",
  "Why did the teacher go to the beach? Because she wanted to test the waters!",
  "Why was the student's report card wet? Because it was below C level!",
   "Why did the student eat his homework? Because the teacher said it was a piece of cake!",
   "Why was the English teacher always calm? Because she had a lot of commas.",
  "What do you call Santa's helpers learning grammar? Subordinate Clauses.",
  "Why did the verb break up with the noun? It felt too constrained.",
  "Why was the possessive pronoun jealous? Because it couldn't handle being around other pronouns.",
  "Why did the comma break up with the period? It felt it needed more space to breathe.",
  "What did the past tense say to the present tense? 'You're just tense.'",
  "Why did the verb go to therapy? It had too many tense issues.",
  "What's the longest word in the dictionary? Smiles, because there's a mile between the first and last letters!",
  "Why did the punctuation mark feel lost? It couldn't find its point.",
  "Why did the grammar book go to therapy? It had too many 'issues.'",
  "Parallel lines have so much in common. It's a shame they'll never meet.",
  "Why was the equal sign so humble? Because it knew it wasn't less than or greater than anyone else.",
  "Why was the math test worried? It had too many problems to solve.",
  "Why did the two fours skip lunch? They already ate.",
  "Why did the biologist go to art class? Because she wanted to learn how to draw blood.",
   "What is the fastest way to determine the sex of a chromosome? Pull down its genes.",
  "What did the biologist wear to impress? Designer genes.",
  "Why did the biologists install a knocker on their door? They wanted to win the no-bell prize.",
  "Why can't you trust an atom? Because they make up everything!",
  "Two atoms are walking down the street. One says to the other, 'Oh no, I think I lost an electron!' The other asks, 'Are you sure?' The first replies, 'Yes, I'm positive!'",
  "Why did the photon check into a hotel? Because it was travelling light!",
  "Why did the quantum physicist only drink root beer? Because when he measured his coffee, he collapsed the waveform!",
  "What did the physicist have for dessert? Pi!",
  "How does a physicist exercise? By pumping ion!",
  "Why did the physics student break up with his biology girlfriend? He realized they had no chemistry.",
  "Why can't you take electricity to social gatherings? Because it doesn't know how to conduct itself!",
  "I told a chemistry joke, but there was no reaction.",
  "What do you call iron blowing in the wind? Febreeze.",
  "What did the zero say to the eight? Nice belt!",
  "I'm reading a book on anti-gravity. It's impossible to put down!",
  "Why do scientists find it easy to go to the beach? Because they have excellent sun-screen!",
  "Why don't skeletons fight each other? They don't have the guts!",
  "Why couldn't the bicycle stand up by itself? It was two-tired!",
  "Why did Alexander the Great go to school? To sharpen his 'conquering' skills!",
  "Why did Julius Caesar buy crayons? He wanted to 'draw' his plans!",
  "What did the grape say when it got stepped on? Nothing, but it let out a little 'wine'!",
  "Why did Napoleon keep his armies in his sleeve? Because he wanted to keep them close to his 'French'!",
  "Why did the archaeologist go bankrupt? Because his career was in ruins!",
  "Why did Joan of Arc stand in the river? Because she wanted to be a 'barbecue'!",
  "Why did Henry VIII have so many wives? Because he didn't have a 'queen'!",
  "Why did the teacher go to Mount Vernon? To visit George Washington's 'classroom'!",
  "Why did Cleopatra refuse to play cards with the Roman emperor? She was afraid he'd 'Caesar'!",
  "Why did the Egyptian pharaoh go to the doctor? Because he was 'sphinx-ing'!",
  "Why did the history book go to therapy? It had too many issues from the past!",
  "Why did the sociology professor bring a ladder to class? Because he heard the course was about social 'climbing'!",
  "Why was the political science student always calm? Because they knew how to 'politic'!",
  "Why did the economics teacher break up with the statistics professor? They didn't see eye to eye on 'supply and demand'!",
  "Why did the archaeologist feel lonely? They were always digging up the past!",
  "Why was the anthropology student a great detective? They could 'unearth' all the clues!",
  "Why did the geography teacher bring a globe to class? They wanted to show the world!",
  "Why did the sociology student excel in sports? They were great at 'socializing'!",
  "Why did the history teacher go to jail? They couldn't stop living in the past!",
  "Why did Shakespeare only write in pen and ink? Because pencils confused him - 2B or not 2B!",
  "Why couldn't Juliet trust Romeo with her wine glass? Because he kept saying, 'O Romeo, Romeo, wherefore art thou Merlot?'",
  "Why did Hamlet's friends refuse to play cards with him? Because he always got 'to be or not to be'!",
  "Why did Macbeth go to the doctor? He had too much ambition!",
  "Why was Dracula always invited to poetry readings? Because he loved 'counting' verses!",
  "Why did the English teacher go to jail? She got caught in a plot!",
  "Why was Mr. Darcy a terrible chef? Because he was always 'prideful' about his 'prejudices'!",
  "Why was Sherlock Holmes always good at solving crimes? He knew how to 'elementary, my dear Watson'!",
  "Why did the poetry book go to therapy? It had too many 'stanza' and 'line' issues!",
  "Why did Oliver Twist always ask for more? He knew the best stories were found in the 'second helping'!",

];

export default jokes;
